version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    resource_class: large
    steps:
      - checkout
      - run: git lfs ls-files -l
      - run: git lfs ls-files -d
  push:
    macos:
      xcode: 14.3.1
    # available for Free plan
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run: |
          cat .gitattributes
      - run: |
          curl https://examples.onelinerhub.com/file.tar.gz -o oneliner.tar
      - run: |
          ls -lah *.tar
      - run: |
          git add oneliner.tar
      - run: |
          git commit -m '[skip ci] add oneliner.tar'
          git checkout -b pushed
          git push origin pushed

workflows:
  main:
    jobs:
      - build
      - push
