version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    resource_class: large
    steps:
      - checkout
      - run: git lfs ls-files -l
      - run: git lfs ls-files -d
  push:
    macos:
      xcode: 14.3.1
    # available for Free plan
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run: |
          cat .gitattributes
      - run:
          name: create 5GB tar file
          command: head -c 5368709120 /dev/urandom > sample5gb.tar
      - run: |
          ls -lah *.tar
      - run: |
          git add sample5gb.tar
      - run: |
          git commit -m '[skip ci] add sample5gb.tar'
          git checkout -b $CIRCLE_WORKFLOW_ID
          git push origin $CIRCLE_WORKFLOW_ID

workflows:
  main:
    jobs:
      - build
      - push
